const restaurantList = [
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "553641",
        name: "Fun Broast",
        uuid: "54b3ff6f-0427-4751-8a20-7923738ee4c8",
        city: "216",
        area: "Kottakkal",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "rzkhgmf5wdkz6oienx2r",
        cuisines: ["Fast Food", "Juices", "Beverages"],
        tags: [],
        costForTwo: 24900,
        costForTwoString: "₹249 FOR TWO",
        deliveryTime: 76,
        minDeliveryTime: 76,
        maxDeliveryTime: 76,
        slaString: "76 MINS",
        lastMileTravel: 9.699999809265137,
        slugs: {
          restaurant: "fun-broast-kottakkal-kottakkal",
          city: "malappuram",
        },
        cityState: "216",
        address:
          "FUN BROAST KOTAKKAL,VALIYAPARAMBU,KOTAKKAL,KOTAKKAL CIRCLE,MALAPPURAM,KERALA,676501",
        locality: "Valiyaparambu\n",
        parentId: 333201,
        unserviceable: true,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4900,
          message: "",
          title: "Delivery Charge",
          amount: "4900",
          icon: "",
        },
        availability: {
          opened: false,
          nextOpenMessage: "Opens next at 11:01 am, today",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.6 kms",
        hasSurge: false,
        sla: {
          restaurantId: "553641",
          deliveryTime: 76,
          minDeliveryTime: 76,
          maxDeliveryTime: 76,
          lastMileTravel: 9.699999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "messageCard",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "messageCard",
      data: {
        message: "Opens next at 11:15 am, today",
      },
      subtype: "info",
      sticky: 1,
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "410345",
        name: "Burger Lounge",
        uuid: "5fb7b33b-2664-4a6b-9fba-9ac7cf5c11d1",
        city: "216",
        area: "Manjeri Locality",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "503b244fa3a21050a78c4a22fd1cf422",
        cuisines: ["Burgers", "Beverages"],
        tags: [],
        costForTwo: 19900,
        costForTwoString: "₹199 FOR TWO",
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        slaString: "42 MINS",
        lastMileTravel: 11.100000381469727,
        slugs: {
          restaurant: "barger-lounge-manjeri-manjeri",
          city: "malappuram",
        },
        cityState: "216",
        address: "KURIKKAL TOWER KACHERIPPADI,MANJERI CIRCLE,MALAPPURAM-676121",
        locality: "Vayapparapadi",
        parentId: 12757,
        unserviceable: true,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4900,
          message: "",
          title: "Delivery Charge",
          amount: "4900",
          icon: "",
        },
        availability: {
          opened: false,
          nextOpenMessage: "Opens next at 11:15 am, today",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "11.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "410345",
          deliveryTime: 42,
          minDeliveryTime: 42,
          maxDeliveryTime: 42,
          lastMileTravel: 11.100000381469727,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
];

export default restaurantList;
